version: '3.6'

services:
  jps:
    image: job-processor-service
    container_name: jps
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  runner:
    image: cosmintitei/bash-curl
    container_name: jps-runner
    command: bash /data/runner.sh
    environment: 
      NUMBER_OF_REQUESTS: 3
    volumes:
      - ./:/data
      
networks:
  default:
    name: jps-network